// import { oflineDataSim } from "./data";
export let oflineDataKendaraan = [
  {
    "api-token": "zSWHVwcT45LeBAvONIdx1pjNDHyDlK7i",
    "status": 200,
    "success": true,
    "message": "Success",
    "api_name": "REST.KendaraanLists",
    "result": {
        "current_page": 1,
        "data": [
            {
                "id": 3,
                "no_polisi": "B 789 POI",
                "nama_pemilik": "Cudo",
                "alamat": "Tangerang",
                "berlaku_stnk": "2018-11-16",
                "berlaku_pajak": "2018-11-13",
                "no_urut": "003",
                "no_skum": "h7899",
                "no_kohir": "kohir003",
                "samsat_provinsi": "Banten",
                "tgl_daftar": "2018-11-23",
                "merk_type": "Hitam",
                "jenis_model": "mobil",
                "tahun_pembuatan": "2018-11-20",
                "warna_kb": "hitam",
                "isi_silinder": "889",
                "no_rangka": "1000",
                "no_mesin": "b7893",
                "coding": "coding",
                "no_bpkb": "09890890898",
                "bahan_bakar": "bensin",
                "warna_tnkb": "hitam",
                "no_polisilama": "dsadas",
                "berat_kb": "10",
                "jumah_sumbu": "3",
                "jbb_penumpang": "6",
                "pajak_bbn_kb": "0",
                "pajak_pkb": "0",
                "pajak_swdkllj": "788934",
                "pajak_adm_stnk": "0",
                "pajak_adm_tnkb": "0",
                "created_at": "2018-11-05 03:16:42",
                "updated_at": "2018-11-05 03:16:42"
            },
            {
                "id": 2,
                "no_polisi": "B 1234 KMN",
                "nama_pemilik": "genjer",
                "alamat": "bekasi",
                "berlaku_stnk": "2018-11-01",
                "berlaku_pajak": "2018-11-02",
                "no_urut": "urut001",
                "no_skum": "skum001",
                "no_kohir": "kohir001",
                "samsat_provinsi": "banten",
                "tgl_daftar": "2018-11-21",
                "merk_type": "honda",
                "jenis_model": "mobil",
                "tahun_pembuatan": "2018-11-14",
                "warna_kb": "hitam",
                "isi_silinder": "889",
                "no_rangka": "1000",
                "no_mesin": "b789",
                "coding": "coding",
                "no_bpkb": "09890890898",
                "bahan_bakar": "bensin",
                "warna_tnkb": "hitam",
                "no_polisilama": "dsadas",
                "berat_kb": "10",
                "jumah_sumbu": "3",
                "jbb_penumpang": "6",
                "pajak_bbn_kb": "0",
                "pajak_pkb": "0",
                "pajak_swdkllj": "788934",
                "pajak_adm_stnk": "0",
                "pajak_adm_tnkb": "10",
                "created_at": "2018-11-04 22:54:38",
                "updated_at": "2018-11-05 03:09:19"
            },
            {
                "id": 1,
                "no_polisi": "B 12344 KMN",
                "nama_pemilik": "AnjarDP",
                "alamat": "bekasi",
                "berlaku_stnk": "2018-11-01",
                "berlaku_pajak": "2018-11-02",
                "no_urut": "urut001",
                "no_skum": "skum001",
                "no_kohir": "kohir001",
                "samsat_provinsi": "banten",
                "tgl_daftar": "2018-11-21",
                "merk_type": "Hitam",
                "jenis_model": "mobil",
                "tahun_pembuatan": "2018-11-14",
                "warna_kb": "hitam",
                "isi_silinder": "889",
                "no_rangka": "1000",
                "no_mesin": "b789",
                "coding": "coding",
                "no_bpkb": "09890890898",
                "bahan_bakar": "bensin",
                "warna_tnkb": "hitam",
                "no_polisilama": "dsadas",
                "berat_kb": "10",
                "jumah_sumbu": "3",
                "jbb_penumpang": "6",
                "pajak_bbn_kb": "0",
                "pajak_pkb": "0",
                "pajak_swdkllj": "788934",
                "pajak_adm_stnk": "0",
                "pajak_adm_tnkb": "0",
                "created_at": "2018-11-04 22:54:15",
                "updated_at": "2018-11-05 04:46:14"
            }
        ],
        "from": 1,
        "last_page": 1,
        "next_page_url": null,
        "path": "http://192.168.43.238:8000/kendaraan",
        "per_page": 10,
        "prev_page_url": null,
        "to": 3,
        "total": 3
    }
  }
];
